server:
  port: 8080
  servlet:
    context-path: /arbeidsgiver-arbeidsforhold-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  profiles:
    active: local

---

spring:
  profiles: local

mock:
  enabled: true
  port: 8081
  aktorPort: 8082

sts:
  stsPass: "mockpass"
  stsUrl: "http://localhost:${mock.port}/sts"

aareg:
  aaregArbeidsforhold: "http://localhost:${mock.port}/aareg-services/api/v1/opplysningspliktig/arbeidsforholdoversikt?status=ALLE"
  aaregArbeidsgivere: "http://localhost:${mock.port}/aareg-services/api/v1/opplysningspliktig/arbeidsgiveroversikt"

yrkeskodeverk:
  yrkeskodeUrl: "http://localhost:${mock.port}/kodeverk/api/"

---

spring:
  profiles: dev

aareg:
  aaregArbeidsforhold: "https://modapp-q0.adeo.no/aareg-services/api/v1/opplysningspliktig/arbeidsforholdoversikt?status=ALLE"
  aaregArbeidsgivere: "https://modapp-q0.adeo.no/aareg-services/api/v1/opplysningspliktig/arbeidsgiveroversikt"

sts:
  stsPass: ${STS_PASS}
  stsUrl: https://security-token-service.nais.preprod.local/rest/v1/sts/token

yrkeskodeverk:
  yrkeskodeUrl: "https://kodeverk.nais.preprod.local/api/v1/kodeverk/Yrker/koder/betydninger?spraak=nb"
