server:
  port: 8080
  servlet:
    context-path: /arbeidsgiver-arbeidsforhold-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  profiles:
    active: local

---

spring:
  profiles: local

no.nav.security.jwt:
  issuers: selvbetjening
  issuer:
    selvbetjening:
      discoveryurl: http://metadata-selvbetjening
      accepted_audience: aud-localhost
      cookiename: localhost-idtoken

mock:
  enabled: true
  port: 8081
  aktorPort: 8082

aareg:
  aaregArbeidsforhold: "http://localhost:${mock.port}/aareg-services/api/v1/opplysningspliktig/arbeidsforholdoversikt?status=ALLE"
  aaregArbeidsgivere: "http://localhost:${mock.port}/aareg-services/api/v1/opplysningspliktig/arbeidsgiveroversikt"

---

spring:
  profiles: dev

aareg:
  aaregArbeidsforhold: "https://modapp-q0.adeo.no/aareg-services/api/v1/opplysningspliktig/arbeidsforholdoversikt?status=ALLE"
  aaregArbeidsgivere: "https://modapp-q0.adeo.no/aareg-services/api/v1/opplysningspliktig/arbeidsgiveroversikt"

no.nav.security.jwt:
  issuers: selvbetjening
  issuer:
    selvbetjening:
      discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
      accepted_audience: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5

---


spring:
  profiles: prod

no.nav.security.jwt:
  issuers: selvbetjening
  issuer:
    selvbetjening:
      discoveryurl: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
      accepted_audience: 45104d6a-f5bc-4e8c-b352-4bbfc9381f25
